lamp:
  generator:
    outputDir: /Users/tangyh/github/lamp-cloud
    frontOutputDir: /Users/tangyh/github/lamp-web
    frontSoyOutputDir: /Users/tangyh/github/lamp-web-pro-soybean
    frontVben5OutputDir: /Users/tangyh/github/lamp-web-vben-max/apps/web-antd
    # 作者
    author: zuihou
    # 默认项目
    projectType: BOOT
  system:
    # 演示环境启用
    notAllowWrite: true
  log:
    ipv4:
      enabled: true
      xdbPath: file:/data_prod/target/ip2region_v4.xdb
    ipv6:
      enabled: true
      xdbPath: file:/data_prod/target/ip2region_v6.xdb

server:
  port: 28760