lamp:
  nextdoc4j:
    license: Powered By zuihou
    licenseUrl: https://github.com/zuihou
    termsOfServiceUrl: https://github.com/zuihou
    version: '@project.version@'
    contact: # 联系人信息
      url: https://github.com/zuihou
      name: zuihou
      email: 306479353@qq.com

springdoc:
  components:
    security-schemes:
      Token:
        type: HTTP
        in: HEADER
        name: Token
        scheme: ''
        description: "请输入 Token，格式： {token}"
      Authorization:
        type: HTTP
        in: HEADER
        name: Authorization
        scheme: 'bGFtcF93ZWI6bGFtcF93ZWJfc2VjcmV0'
        description: "客户端信息"
      ApplicationId:
        type: HTTP
        in: HEADER
        name: ApplicationId
        scheme: '1'
        description: "应用ID"
  # 默认是false，需要设置为true
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: ${nextdoc4j.enabled}
    path: /v3/api-docs
  group-configs:
    # @lamp.generator auto insert springdoc.groupconfigs
    - group: 'oauth_auth'
      displayName: '认证服务'
      paths-to-match: '/**'
      packages-to-scan: top.tangyh.lamp.oauth
    - group: 'base_base'
      displayName: 'base-基础模块'
      paths-to-match: '/**'
      packages-to-scan: top.tangyh.lamp.base
    - group: 'base_file'
      paths-to-match: '/**'
      displayName: 'base-文件模块'
      packages-to-scan: top.tangyh.lamp.file
    - group: 'base_msg'
      paths-to-match: '/**'
      displayName: 'base-消息模块'
      packages-to-scan:
        - top.tangyh.lamp.msg
        - top.tangyh.lamp.sms
    - group: 'system'
      displayName: '系统管理'
      paths-to-match: '/**'
      packages-to-scan: top.tangyh.lamp.system.controller
    - group: 'generator'
      displayName: '代码生成器'
      paths-to-match: '/**'
      packages-to-scan:
        - top.tangyh.lamp.generator
        - top.tangyh.lamp.test.controller

# NextDoc4j 在线文档配置
nextdoc4j:
  # 生产环境如需彻底屏蔽文档，改为 false 即可
  enabled: true
  plugin:
    security:
      # 启用认证展示与调试自动注入
      enabled: true
  # 文档访问密码（basic auth），生产环境请务必修改
  auth:
    enabled: true
    password: lamp
  extension:
    enabled: true
    brand:
      title: lamp-cloud 在线文档
      footer-text: Apache License 2.0 | Copyright  2020 [lamp-cloud](https://github.com/zuihou)
